### ISSUE TITLE
[12.0][IMP] purchase_work_acceptance  :: WA, new field “Invoice Reference”

### ISSUE THREAD

**Issue by kittiu** [ecosoft-odoo/kanban#11]
- And when Vendor Billed is create by WA, set this field to Vendor Bill too.

**Comment by kittiu** [comment]
@ps-tubtim this this ready? If so, please link the PR here too.

**Comment by kittiu** [comment]
@ps-tubtim ready for review? Where is the PR?
Note: please communicate more, it will help the reviewer.

**Comment by ps-tubtim** [comment]
This link: https://github.com/OCA/purchase-workflow/pull/774
I improve it on [12.0][WIP] purchase_work_acceptance #774

**Comment by kittiu** [comment]
OK, I will check.

Note:
* In the future, best is to use separated PR for each issue. But if that is not possible, dont't commit amend, so you can point me the commit for this feature. After all the review is done, we can merge commit later.

**Comment by kittiu** [comment]
The "Invoice Reference" in WA, will overwrite the "Vendor Reference" in Vendor Bill (even PO also have Vendor Reference".
We should have new field "Invoice Reference" in Vendor Bill also.

**Comment by kittiu** [comment]
OK, let's say this one is fine for now.
