### ISSUE TITLE
#1917 Add goods category

### ISSUE THREAD

**Issue by kittiu** [ecosoft-odoo/kanban#27]
- อาหารและเครื่องดื่ม
- ของตกแต่ง
- ของฝาก
- เสื้อผ้าและเครื่องประดับ
- อื่นๆ

Issue >> http://128.199.123.133:10083/issues/1917
PR >> https://github.com/ecosoft-odoo/acm/pull/29

**Comment by newtratip** [comment]
Wait P'Lek Review

**Comment by newtratip** [comment]
![Selection_301](https://user-images.githubusercontent.com/24691983/68638592-a69d8200-0534-11ea-82ae-15521b4539f1.png)
