### ISSUE TITLE
#1916 Breach Agreement

### ISSUE THREAD

**Issue by kittiu** [ecosoft-odoo/kanban#28]
We want to track the number of breaches as well as look at the underlying reasons
* Breach Date
* Breach Type
* Breach Reason
* แก้ไขด้วย วิธีอะไร
* timestamp เลิก breach วันที่เท่าไร

Issue >> http://128.199.123.133:10083/issues/1916

**Comment by newtratip** [comment]
Wait P'Lek Review

**Comment by newtratip** [comment]
**Breach**
![Selection_294](https://user-images.githubusercontent.com/24691983/68637894-8a004a80-0532-11ea-8809-f13d2ac7138e.png)
![Selection_296](https://user-images.githubusercontent.com/24691983/68638074-02ffa200-0533-11ea-9707-e2d08c35e825.png)

**Cancel Breach**
![Selection_298](https://user-images.githubusercontent.com/24691983/68638261-8f11c980-0533-11ea-92ba-cbc65bc5a7b9.png)
![Selection_299](https://user-images.githubusercontent.com/24691983/68638303-afda1f00-0533-11ea-9bef-3d40863f7c5d.png)
![Selection_300](https://user-images.githubusercontent.com/24691983/68638519-68a05e00-0534-11ea-8f30-627491c49d09.png)
