### ISSUE TITLE
#1907 Transfer Agreement

### ISSUE THREAD

**Issue by kittiu** [ecosoft-odoo/kanban#31]
* Should ask the user if we will return the security deposits
* Should automate the creation of a transfer fee invoice to the old Lessee
http://128.199.123.133:10083/issues/1907

**Comment by newtratip** [comment]
ระบบ copy จากสัญญาใบเก่าไปเป็นสัญญาใบใหม่ + เปลี่ยนชื่อ partner, วันที่ทำสัญญา, วันที่เริ่มต้นสัญญา, วันที่สิ้นสุดสัญญา
![Selection_312](https://user-images.githubusercontent.com/24691983/68639836-6dffa780-0538-11ea-940b-f9c56c47c49d.png)
![Selection_313](https://user-images.githubusercontent.com/24691983/68639966-dbabd380-0538-11ea-949e-5cf1627c2f02.png)
![Selection_314](https://user-images.githubusercontent.com/24691983/68639976-e2d2e180-0538-11ea-94df-41881c9345fe.png)

**Note**
* เรื่อง automate ยังไม่ได้ทำ อาจจะต้องทำ manual ไปก่อน ถ้าระบบคงที่ถึงจะเริ่มทำ automate ได้
