### ISSUE TITLE
#1908 Extension Agreement

### ISSUE THREAD

**Issue by kittiu** [ecosoft-odoo/kanban#32]
* เปลี่ยนชื่อ button จาก Extend เป็น Renew
* สามารถ Extension Contract ได้หลายๆใบพร้อมกัน โดยมี criteria คือ
* % ของการเพิ่มค่าเช่า,ค่าตอบแทน,ค่าแป๊ะเจี๊ยะ
Issue >> http://128.199.123.133:10083/issues/1908

**Comment by newtratip** [comment]
เพิ่มความสามารถให้ Extend ได้หลายใบพร้อมกัน
![Selection_305](https://user-images.githubusercontent.com/24691983/68638918-9a65f480-0535-11ea-9d76-a4d76a3541c4.png)
![Selection_309](https://user-images.githubusercontent.com/24691983/68639291-aaca9f00-0536-11ea-9b35-65e399a9582c.png)
![Selection_311](https://user-images.githubusercontent.com/24691983/68639389-fc732980-0536-11ea-8c54-cde10c9de070.png)

**ข้อจำกัด**
* ไม่สามารถแก้ไขจำนวนปีของการต่อสัญญาได้ เช่น สัญญาที่ 1 มีสัญญาเช่า 3 ปี เมื่อต่อสัญญาควรจะเป็นสัญญาเช่า 3 ปี (เพราะระบบไม่รู้ว่าควรจะคำนวณ duration ใน products/services อย่างไร **ถ้ามีหลักการตายตัว คิดว่าน่าจะทำตามหลักการนั้นได้**)
* วันที่ใน duration products/services ควรจะตรงกันทั้ง 2 สัญญา (สัญญาใบเดิมกับสัญญาใบใหม่ เหตุผลเดียวกับ point ข้างบน)
* % การเพิ่มค่าเช่า (ไม่แน่ใจมีหลักการคำนวณยังไง)
