### ISSUE TITLE
#1909 Terminate Agreement

### ISSUE THREAD

**Issue by kittiu** [ecosoft-odoo/kanban#33]
Issue >> http://128.199.123.133:10083/issues/1909

**Comment by newtratip** [comment]
wait P'Lek Review

**Comment by newtratip** [comment]
![Selection_302](https://user-images.githubusercontent.com/24691983/68638695-ea908700-0534-11ea-92d5-0f271e0ca6e8.png)
![Selection_303](https://user-images.githubusercontent.com/24691983/68638731-fe3bed80-0534-11ea-9775-bf480afddd32.png)
![Selection_304](https://user-images.githubusercontent.com/24691983/68638772-24fa2400-0535-11ea-89e1-b4b657e3c04c.png)
