### ISSUE TITLE
#1910 List view column to display on agreement

### ISSUE THREAD

**Issue by kittiu** [ecosoft-odoo/kanban#34]
Reference (identity code, contract year-contract code, format: YYYY-xxxx, e.g. 2019-0001)
Title (ชื่อของสัญญา user กรอกเอง)
Partner --> Change to "Lessee"
Zone --> Add
Product Category --> Add
Lock Add
Company --> Change to "Lessor"
Start Date (Agreement start date)
End Date
Agreement Type --> Delete
Agreement Sub-Type --> Delete
Status

Issue >> http://128.199.123.133:10083/issues/1910

**Comment by newtratip** [comment]
จากที่ request มา มีบาง column ผมยังไม่ delete นะครับ (เผื่ออนาคตอาจต้องการ)
**Issue**
![Selection_324](https://user-images.githubusercontent.com/24691983/68664546-12064480-0573-11ea-8ff9-1246905ce820.png)

**แก้ไข (แสดงเฉพาะในตัวสัญญา ไม่แสดงใน template)**
![Selection_323](https://user-images.githubusercontent.com/24691983/68664623-38c47b00-0573-11ea-9773-be16d979f468.png)
