### ISSUE TITLE
#1913 Move field in partner page

### ISSUE THREAD

**Issue by kittiu** [ecosoft-odoo/kanban#35]
* Move Title to a position before name input
* Move Tax ID to below Name
Issue >> http://128.199.123.133:10083/issues/1913

**Comment by newtratip** [comment]
![Selection_322](https://user-images.githubusercontent.com/24691983/68654078-c5fdd480-055f-11ea-967c-47fe68f7ebe5.png)

PR >> https://github.com/ecosoft-odoo/acm/pull/40
